### ISSUE TITLE
Add collection field in model

### ISSUE THREAD

**Issue by DerouineauNicolas** [Web-Multi-Media/HttpStreamingServer#14]
Following discussions in PR #8, it was suggested that we could add a collection field in the model.

**On the backend side:** the field could be filled by the directory where the asset is registered. If the asset is in the root directory, we'll asume it's part of no collection. For the initial get_videos/ API request, we should return only one asset per collection.
The collection field should be a many2one relation.
I think this also implies the creation of an API to retrieve videos in a collection.

**On the frontend side** : The whole idea is to display only one thumbnail per collection (at least in the main page of the app). Then, if the thumbnail is clicked, a call to /collection/collectionid/ API is done.

**Comment by DerouineauNicolas** [comment]
After some readings on REST API, I suggest the following modification for the backend API:

GET /video/ => retrieve the list of all videos 
GET /video/videoid => retrieve only a video 
GET /collection/ => retrieve the list of all collection
GET /collection/collectionid/ => retrieve the list of video

I think it the initial frontend API call should be be done on /collection/ instead of /video/.

**Comment by xavierfav** [comment]
IMO this suggestion on the modification of the API should be addressed in an other issue since it is not directly related to this issue.

**Comment by xavierfav** [comment]
After discussing the next steps for organizing our collection of video, we decided that we will:
- Use subliminal to get (parsed from the video filename):
   - Movie/Series
   - Title
   - Episode & Season for series
- Add and index these information in the database
- Metadata could be extended by for instance using an IMDB API. We leave that for a future step.


I propose the following model:
```
Video
    series ForeignKey to Series
    movie ForeignKey/OnToOne to Movie (probably some movies can have several episodes 
        that can be linked to the same Movie instance, we will see that while 
        programming what comes more naturally).
    episode IntField (default to None, used only when it makes sense)
    season IntField (default to None, used only for video linked to a Series instance)
    ...

Series
    title

Movie
    title
```

@DerouineauNicolas What do you think?

**Comment by DerouineauNicolas** [comment]
Ok this looks good to me ! The only cornercase for me is how to deal with the situation when no info about movie/series is retrieved by subliminal.

**Comment by xavierfav** [comment]
I haven't been able to make subliminal retrieve metadata from existing online resources.
In fact it seems that it is just able to get the information mentioned before from the video filename.

We could try one of the IMDB API in order to get more information in the future.

**Comment by worms19** [comment]
For the front-end part i think it would be easier to have several requests :

-One to get all disctincts movies (maybe with pagination if we get big enough)
-Same for tv shows 
-the search bar should have a picklist to choose between tv show and movies
-a request to get all the seasons from a tv show
-another one to get all the episodes of a season (paginated ?)

**Comment by xavierfav** [comment]
Having a parameter to search on series or movies is a good idea!
For the Series, we can easily provide the kind of queries you are asking for,
I guess we could have a carousel per series and seasons also. So you can navigate into the different hierarchy levels (series, seasons, episodes).

At the top of the page, we could keep a path of the progression which could be used for navigating "backward", e.g.:
Series > Malcolm > Season 2
or 
Movies > The Lord of The Rings

**Comment by xavierfav** [comment]
Typical scenario for retrieving an episode from the wire series.

1. - select video type (Series or Movies) by using the dropdown
    - type query
    - select series by clicking on one element of the carousel
2. select a season by clicking on one element of the carousel
3. select episode by clicking on one element of the carousel
![IMG_20200101_183646](https://user-images.githubusercontent.com/10927428/71644281-2f7ba300-2cc6-11ea-81d8-85ff6ba3221b.jpg)

The path at the top allows to navigate back.
We could also add dropdown for Seasons and Episodes.

**Comment by xavierfav** [comment]
After discussing with @worms19, we thought it would be maybe more appropriate to use a dropdown (or other kind of input) for selecting the series seasons, instead of using the carousel.
This modifies step 2 above, where `Seasons `at the end of the path, could be a dropdown.

**Comment by DerouineauNicolas** [comment]
For me, the overall design is OK. When the user initially arrives on the page,  I would be in favor of displaying two carrousels (one for movies, one for series). The carroussels for series would expose one thumbnails per series and would then follow the design you mentionned.

**Comment by xavierfav** [comment]
Mh, I am a bit confuse if we add a second carousel, then it is changing the logic.
So, please, can you propose a precise scenario of the idea you have in mind?

**Comment by DerouineauNicolas** [comment]
My scenario would be the following:

![scenario1](https://user-images.githubusercontent.com/22216508/71821056-5ef92980-3091-11ea-82cb-d6bdff0168f3.jpg)

It would enable the user to switch directly from a movie to a tv show.

**Comment by xavierfav** [comment]
If I understand correctly, we would have on path per carousel?
And one search input for both?
It seems nice but it involves much more work that only having one carousel.
Switching to movies is not something I personally do when I am watching a series.
Why don't we start with one carousel, which a selector for deciding movie or series, and then we see if we expand it to have both carousel at the same time?

@worms19 what do you think?

**Comment by DerouineauNicolas** [comment]
I would keep only one search bar, which would be querying both Series and Movies API (therefore updating both carrousel at the same time). I agree that this can be a future update and I'm fine with the initial step you propose.

Let's see what is @worms19 opinion.

**Comment by valeneri** [comment]
I like the idea of having only one carousel and the breadcrumb to easily navigate back.

In case of series, it may also be a nice option to select the season then the episode direcly from the carousel.

**Comment by xavierfav** [comment]
In the backend app and in the API client we need to:
- Make a generic search function in models.py
- Use it in class methods of Videos, Movies and Series to search videos, movies and series respectively.
- Add method in Series to get videos (with optional argument for selecting videos from a season)
- Add method in Series to get one video of a specific season and episode.
- Add a method in Series to get the number of existing seasons in the db.
- Add method in Movie to get its videos (It may happen that several movies are linked to the same movie. We should try with for instance a movies that has episodes like Star Wars or The Lord of The Rings).
- Add test for parsing Movie episodes.
- Add API viewsets corresponding to search_series, get_series (to get one episode from a season), search_movies, get_series_seasons, get_movie.
In the API client, we should add one method for each of these viewsets.


@DerouineauNicolas seemed motivated to work on these things. Let me know what do you think.

**Comment by xavierfav** [comment]
Things left to do:
- tests
- API Client
