### ISSUE TITLE
Improve API

### ISSUE THREAD

**Issue by DerouineauNicolas** [Web-Multi-Media/HttpStreamingServer#15]
After some readings on REST API, I suggest the following modifications for the backend API:

GET /videos/ => retrieve the list of all videos
GET /videos/videoid => retrieve only a video
GET /collections/ => retrieve the list of all collections
GET /collections/collectionid/ => retrieve the list of videos in a collection

I think it the initial frontend API call should be be done on /collection/ instead of /video/.

**Comment by DerouineauNicolas** [comment]
Partially addressed by 0ddb01bfba7e57a6ea5be31fb4e744cd51522aa2

**Comment by DerouineauNicolas** [comment]
It was decided in an offline conversation that Django Rest Framework will replace the current API.

**Comment by DerouineauNicolas** [comment]
The current hack of deserialization/serialization used [here](https://github.com/Web-Multi-Media/HttpStreamingServer/blob/master/backend/StreamServerApp/views.py#L65) will be corrected with the following code using DRF:

`class CustomPagination(pagination.PageNumberPagination):
    def get_paginated_response(self, data):
        return Response({
            'links': {
                'next': self.get_next_link(),
                'previous': self.get_previous_link()
            },
            'count': self.page.paginator.count,
            'results': data
        })
`

This will have impact in the frontend code mostly [here] (https://github.com/Web-Multi-Media/HttpStreamingServer/blob/master/frontend/src/components/VideoCarrouselSlick.js#L71). 
Instead of using the number of pages, we can test if the server response contains a valid "next" field.

**Comment by xavierfav** [comment]
I think this is a nice idea, but includes more work in back and front.
Why not using the default paginator that is already included when using the generic views or viewset?
Is the generic views or viewset ok for our use?

**Comment by DerouineauNicolas** [comment]
You're right, the default paginator seems ok. Viewset are perfectly suited for our need.

**Comment by worms19** [comment]
front has been corrected after server changes i think we can close the issue

**Comment by DerouineauNicolas** [comment]
Fixed by PR#23
