### ISSUE TITLE
Production web sever running in debug mode

### ISSUE THREAD

**Issue by xavierfav** [Web-Multi-Media/HttpStreamingServer#18]
The production web server is running in debug mode.
This is absolutly not recommended.

We should change that given that it is very easy to do.
In [here](https://github.com/Web-Multi-Media/HttpStreamingServer/blob/master/backend/StreamingServer/settings.py#L51), we should add a logic like:
```python
if os.getenv('DEPLOY_ENV', 'dev') == 'prod':
    DEBUG = False
else:
    DEBUG = True
```

Also an environement variable `DEPLOY_ENV `should be set to 'prod' in production.
Do we have a secret .env file in the server or somewhere were we could add it?
Maybe it would be a good idea to create a private repo for the deploy of our application.
Fabric is a nice library for easy deployment, I don't know if it is appropriate for us.

**Comment by DerouineauNicolas** [comment]
Should be fixed by #22
