### ISSUE TITLE
React djangoAPI does not automatically adapt endpoint for prod & dev

### ISSUE THREAD

**Issue by xavierfav** [Web-Multi-Media/HttpStreamingServer#19]
The endpoint which the client has to request is defined in [here ](https://github.com/Web-Multi-Media/HttpStreamingServer/blob/master/frontend/src/api/djangoAPI.js#L5).

Everytime we do development, we have to manually change the endpoint.
This is not pratical, and do not facilitate CI.

We should programatically set the endpoint to what is needed.
[Here ](https://medium.com/@trekinbami/using-environment-variables-in-react-6b0a99d83cf5)are some examples.

**Comment by DerouineauNicolas** [comment]
Fixed by 30f598e45135e0f2d737821be2e8d16fb34772f2
