### ISSUE TITLE
Add logging system

### ISSUE THREAD

**Issue by xavierfav** [Web-Multi-Media/HttpStreamingServer#21]
Currently we use `print` to log things on the terminal.
We should setup a proper logging system ASAP.
[Djago logging documentation](https://docs.djangoproject.com/fr/2.2/topics/logging/).

It will need a bit of configuration in the django settings file.
I guess we don't need to have many handlers and loggers for now.
I am also not sure what would be the best way to organise our logs.
Maybe we could think also of using a log management software like Graylog, or maybe just an error tracking software like Sentry for spotting exceptions.

**Comment by DerouineauNicolas** [comment]
Fixed by commit 25ff1a34620fefb52a3ab8e0f13d2e08eed7fa73
