### ISSUE TITLE
Split API client & UI logic

### ISSUE THREAD

**Issue by xavierfav** [Web-Multi-Media/HttpStreamingServer#26]
It would be very convenient to have a API client implementation separated from the user interaction logic.

We could maybe have in the [`djangoAPI.js`](https://github.com/Web-Multi-Media/HttpStreamingServer/blob/master/frontend/src/api/djangoAPI.js) file a client implemented.
We could use objects referring to concepts like a pager, a search, a video, etc...

Maybe would make sense to also switch to using React Hooks for implementing the API Client (example [here](https://blog.bitsrc.io/making-api-calls-with-react-hooks-748ebfc7de8c)).
@worms19 what is your thought about that?

I see also simple approaches with classes that look good to me (example [here](https://dev.to/oktadev/build-a-simple-crud-app-with-python-flask-and-react-30k5), scrolling deep)

**Comment by valeneri** [comment]
I'm not sure it would be a good idea to mix hooks with states.
We could possibly switch to hooks but in this case we'll have to rewrite everything.

Therefore I agree with the idea of declaring every methods related to the API in a class (or several) in a separate file.

**Comment by worms19** [comment]
hooks and states are made to live together cf React thoughts on hooks.

we don't need to rewrite existing code but it would be a good practice to use hooks in the future !

**Comment by xavierfav** [comment]
I think the code needs to be re-written.
The idea would be that the API client could be re-used by any app, could be easily maintained, extended and tested.
Right now the everything is mixed in our app, which does not allow us to easily modify the API without breaking the existing code.
