### ISSUE TITLE
Add User account

### ISSUE THREAD

**Issue by DerouineauNicolas** [Web-Multi-Media/HttpStreamingServer#4]
It could be interesting to have an upload feature in the frontend (although this implies to manage some admin accounts).

**Comment by xavierfav** [comment]
So, as I understand, two things have to be done here:

- Add user accounts
- Add upload feature

How are you thinking to do the user accounts? 
Could we rely on third party services and do social authentication (login with google, etc...)?

**Comment by DerouineauNicolas** [comment]
Maybe this feature should be split in two different issues (if would be nice to have a interdependancy tracker for issue on github, but that's another story).

Anyway, I saw some working examples on how to use Token Authentication and JWT with Django and react, so this seems to be doable in a reasonable amount of time (http://v1k45.com/blog/modern-django-part-4-adding-authentication-to-react-spa-using-drf/).

On the other hand, I didn't find any project using social auth with django and react, do you think it's easily doable ?

**Comment by xavierfav** [comment]
I agree it should be spitted in two different issues.

The thing with creating user accounts, is that we are then managing personal data, which implies a lot of stuff to do (GDPR). With Social Auth, we could no get any information from the user third party account, which would simplify things.

I don't understand why normal Django apps for social auth would not work with react.
These ones for examples:

- [django-allauth](https://django-allauth.readthedocs.io/en/latest/)
- [Python Social Auth](https://github.com/python-social-auth/social-app-django)

**Comment by DerouineauNicolas** [comment]
I was affraid that django-allauth and SocialAuth was only relying on django templating system, but it's not so cool. I found this project as well:

https://github.com/ZachLiuGIS/reactjs-auth-django-rest

**Comment by DerouineauNicolas** [comment]
I think we could avoid to store personnal data and use anonymous informations (for example, just store login and viewing history). The only thing I'm not sure is If the viewing history lies under the anonymous data or not.

On a side not,  [this plugin](https://github.com/davesque/django-rest-framework-simplejwt) seems to be a good starting point if we decide to use JWT for auth.

**Comment by xavierfav** [comment]
But for registering, no e-mail adress would be asked then?
How would be the process?
Maybe we should not allow people to register, and the add of accounts should be manager by the maintainer only?

Storing user behaviors such as his viewing history does not require to store any personal data.

If we give numerical random identifiers for users, there should be no problem.
[
More info about what is considered personal data](https://ec.europa.eu/info/law/law-topic/data-protection/reform/what-personal-data_en)

**Comment by DerouineauNicolas** [comment]
I think the critical missing feature would be password recovery if we don't ask for an email adress, but apart from that, I don't see the need for an email adress.

JWT would allow us to start with a minimal implementation of authentication. Nothing prevents us to add GDPR related data in the future.

**Comment by xavierfav** [comment]
What do you mean by "add GDPR related data in the future"?
Anyway, the website is not meant to be used by anyone right? 
So if we don't allow any form of automatic signup, and we restrict the use of the app to only closed friends, I don't see any need for complying with the GDPR.

**Comment by DerouineauNicolas** [comment]
>> What do you mean by "add GDPR related data in the future"?

I mean we can store email/name/religion in the future if we feel the need (with all the extra care needed by GDPR). This is purely hypotethical (and not expected on my side).

>> Anyway, the website is not meant to be used by anyone right?

I don't know. I feel there is several usecases (out of the basic movie/tv show streaming) where a sign up page would be useful. Maybe we could leave that decision to the people deploying the application (maybe as settings or in a configuration page ?).

**Comment by xavierfav** [comment]
Interesting!
We should maybe decide on a license for distribution the code if it is meant to be re-used by other people in their own (maybe private) context.
