### ISSUE TITLE
Subtitles Upload 

### ISSUE THREAD

**Issue by DerouineauNicolas** [Web-Multi-Media/HttpStreamingServer#41]
PR #40 added the option to handle custom subtitles locally. It would be nice to upload them to the server.

A first approach would be to modify the current Video model (remove the subtitle field), create a new Subtitle model which would then contain a foreign key pointing to the Videopk (many2one relationship).
A new API called /subtitles/videopk/ would then return all the subtitles associated with a video.

The upload would then be handled with a POST call.

@xavierfav, any thought on that ?

**Comment by xavierfav** [comment]
If I understand correctly, you propose to add a `Subtitle` model, and use a many2one relation.
I see several things:
- First, if you create a `subtitle` field in the `Video` model, it  would not be a `many2one` relationship but a `one2many`. So the way to go in Django would be to define the relation field in the `Subtitle` model instead, where you could use a `many2one` (`ForeignKey`).
- Then, as I already mentioned you, maybe we could avoid using a database table for storing these relations? A [`JSONFIeld`](https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/fields/#jsonfield) in the `Video` model would offer the flexibility of adding as many subtitle files as we want without having to complexify our database queries. We could very quickly have from the client, an object that lists all the subtitles. And finally, the subtitles could be added dynamically in the video component.
- Have in mind the work of @yvan-chamoin. He added some fields related to the subtitles, and I already thought that switching to `JSONField` could simplify his work too.
- For the upload, I think it should be quite easy to set it up, however, we need a nice form, and I think only logged in users (and trustable) should be able to upload subtitle files.

**Comment by DerouineauNicolas** [comment]
- Sure, my bad, this was my initial intent (I'm gonna edit my first suggestion).
- There is several drawbacks to using JSONField. What happens if we want to perform filtering or query on the subtitles ? I'm not opposed to this approach, but I fear a lack of flexibility in the future.
- I think both approaches should fit with his work.

**Comment by xavierfav** [comment]
- you can filter and index things inside a JSONField, you can refer to the documentation.
- I was thinking of facilitating the work of Yvan and us all, as much as possible.

**Comment by xavierfav** [comment]
After internal discussion, we decided to go for the model-based approach that @DerouineauNicolas proposed, which is cleaner.

- We should see what relation field we use in the serializer. Maybe we can rely on a [nested relationship](https://www.django-rest-framework.org/api-guide/relations/#nested-relationships).
- This relation field should appear only on the `VideoSerializer `and not in the `VideoListSerializer`.
- We should include different things in the subtitle table:
  - path to original subtitle.srt file (for @yvan-chamoin work on auto subtitle sync)
  - path to the web subtitle file
  - type (source/subliminal/user-provided/auto-sync)
  - video -> `ForeignKey`
  - created_at
  - created_by
  - language
  - ...?
- The front and the API client should be adapted and also we should dynamically add the subtitles field in the video component.
