### ISSUE TITLE
Viewing history

### ISSUE THREAD

**Issue by DerouineauNicolas** [Web-Multi-Media/HttpStreamingServer#5]
It could also be interesting to have a viewing history per user basis. This could allow the user to take back the movie where he started.

**Comment by xavierfav** [comment]
Good idea!
This can be done in several ways.
I think that we can do a `user_watching` relation Many2Many User - Video.
Have the `through` parameter set to a table like that:

```python
class UserVideoHistory(models.Model):
  user = models.ForeignKey(User)
  video = models.ForeignKey(Video)
  time =  models.IntegerField()   # time in ms
```

We would need a User table for that, which we also need for #4.

**Comment by DerouineauNicolas** [comment]
We need to add a .setToken() method to djangoAPI.js (https://github.com/Web-Multi-Media/HttpStreamingServer/blob/master/frontend/src/api/djangoAPI.js) to handle history related method.
